# === Task 4 — Agent configuration (scanner + patcher) ===
server_url: "http://127.0.0.1:8000"  # FastAPI manager URL
agent_token: ""                      # will be filled by register_agent.py
auto_patch: false                    # true = install updates automatically
patch_scope: "os"                    # os | pip | all
interval_minutes: 60                 # loop mode period in minutes
